//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using teacher.Data.Models;
namespace teacher.Data
{
    public partial class TeacherEntities : DbContext
    {
        public TeacherEntities()
            : base("name=TeacherEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }

        public DbSet<T_SysMenus> T_SysMenus { get; set; }
        public DbSet<T_User> T_User { get; set; }
        
    }
}