//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("T_AbsentResult")]
    public partial class T_AbsentResult
    {
        /// <summary>
        /// 请假编号
        /// </summary>
        [Key]
        [MaxLength(32)]
        public string AbsentID { get; set; }
        /// <summary>
        /// 学号
        /// </summary>
        [MaxLength(32)]
        public string StudentCode { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        [MaxLength(50)]
        public string StudentName { get; set; }
        /// <summary>
        /// 请假原因
        /// </summary>
        [MaxLength(500)]
        public string Reason { get; set; }
        
        /// <summary>
        /// 请假时间起
        /// </summary>
        public Nullable<System.DateTime> AbsentTimeBegin { get; set; }
        /// <summary>
        /// 请假时间止
        /// </summary>
        public Nullable<System.DateTime> AbsentTimeEnd { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
