//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("T_LotteryUsers")]
    public partial class T_LotteryUsers
    {
        [Key]
        [MaxLength(32)]
        public string LotteryGroupID { get; set; }
        /// <summary>
        /// 学生姓名
        /// </summary>
        [MaxLength(50)]
        public string StudentName { get; set; }
        /// <summary>
        /// 学号
        /// </summary>
        [MaxLength(20)]
        public string StudentCode { get; set; }
    }
}
