//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("T_Question")]
    public partial class T_Question
    {
        /// <summary>
        /// 问题编号
        /// </summary>
        [Key]
        [MaxLength(32)]
        public string QuestionID { get; set; }
        /// <summary>
        /// 考试编号
        /// </summary>
        [MaxLength(32)]
        public string ExamID { get; set; }
        /// <summary>
        /// 题号
        /// </summary>
        public Nullable<System.Decimal> QuestionNo { get; set; }
        /// <summary>
        /// 问题
        /// </summary>
        [MaxLength(2000)]
        public string Question { get; set; }
        /// <summary>
        /// 答案
        /// </summary>
        [MaxLength(2000)]
        public string Answer { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [MaxLength(300)]
        public string Remark { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [MaxLength(100)]
        public string Types { get; set; }
        /// <summary>
        /// 分数
        /// </summary>
        public Nullable<System.Decimal> Score { get; set; }
    }
}
