//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("T_Score")]
    public partial class T_Score
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [Key]
        [MaxLength(32)]
        public string ScoreID { get; set; }
        /// <summary>
        /// 考试编号
        /// </summary>
        [MaxLength(32)]
        public string ExamID { get; set; }
        /// <summary>
        /// 学号
        /// </summary>
        [MaxLength(20)]
        public string StudentCode { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        [MaxLength(50)]
        public string StudentName { get; set; }
        /// <summary>
        /// 班级
        /// </summary>
        [MaxLength(100)]
        public string StudentClass { get; set; }
        /// <summary>
        /// 科目
        /// </summary>
        public string Course { get; set; }
        /// <summary>
        /// 分数
        /// </summary>
        public Nullable<System.Decimal> Score { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
