//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("T_Students")]
    public partial class T_Students
    {
        /// <summary>
        /// 学号
        /// </summary>
        [Key]
        [MaxLength(20)]
        public string StudentCode { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        [MaxLength(50)]
        public string StudentName { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        public bool Sex { get; set; }
        /// <summary>
        /// 生日
        /// </summary>
        public Nullable<System.DateTime> BirthDay { get; set; }
        /// <summary>
        /// 班级
        /// </summary>
        [MaxLength(100)]
        public string StudentClass { get; set; }
        /// <summary>
        /// 在读情况
        /// </summary>
        public bool StudyStatus { get; set; }
        /// <summary>
        /// 入学年份
        /// </summary>
        public int EnrollmentYear { get; set; }
    }
}
