//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("T_User")]
    public partial class T_User
    {
        [Key]
        public string UserID { get; set; }
        public string UserPSW { get; set; }
        public string UserNickName { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    }
}
